spring.application.name=GX Sneaker


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java6N_fa25;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true