spring.application.name=GX Sneaker

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GX_SNEAKER4;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luanchamhoc261@gmail.com
spring.mail.password=totb yqmb yqvh vijs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=E:/DATN/DATN/GX Sneaker/uploads/avatars

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

payos.client-id=f926a8b5-1d8c-4d58-a8ec-be9c2a0507d6
payos.api-key=d0d4dd60-36ee-4c11-b732-b86dc2e2c44c
payos.checksum-key=e408ec9001675269891f1d0511b5d4780da41870b5ea0a4f326bd79e19498f58

#app.frontend-url=http://localhost:5173